import streamlit as st
import joblib
import pandas as pd
import re
import os

# Set page config
st.set_page_config(
    page_title="AI Text Detector",
    page_icon="🤖",
    layout="wide",
    initial_sidebar_state="collapsed"
)

# Load custom CSS
css_path = os.path.join(os.path.dirname(__file__), 'style.css')
with open(css_path) as f:
    st.markdown(f'<style>{f.read()}</style>', unsafe_allow_html=True)

# Helper functions for analysis
def analyze_signatures(text):
    # Formal transitions (AI signatures)
    formal_words = ['however', 'consequently', 'furthermore', 'nevertheless', 'overall', 'in conclusion', 'moreover']
    formal_count = sum(1 for word in formal_words if re.search(rf'\b{word}\b', text.lower()))
    
    # Personal pronouns (Human signatures)
    personal_pronouns = ['i', 'my', 'me', 'we', 'our', 'us', 'you', 'your']
    human_count = sum(1 for word in personal_pronouns if re.search(rf'\b{word}\b', text.lower()))
    
    # Informal fillers
    informal_words = ['basically', 'literally', 'honestly', 'pretty', 'cool', 'stuff', 'vibes', 'bro']
    informal_count = sum(1 for word in informal_words if re.search(rf'\b{word}\b', text.lower()))
    
    return {
        'formal_score': formal_count,
        'human_score': human_count + informal_count
    }

# Load model and vectorizer
@st.cache_resource
def load_artifacts():
    try:
        model_path = os.path.join(os.path.dirname(__file__), 'lr_model.joblib')
        vectorizer_path = os.path.join(os.path.dirname(__file__), 'tfidf_vectorizer.joblib')
        model = joblib.load(model_path)
        vectorizer = joblib.load(vectorizer_path)
        return model, vectorizer
    except:
        return None, None

model, vectorizer = load_artifacts()

# UI Layout
st.markdown('<div class="main-header"><h1>AI vs Human Detector</h1><p>NLP-Powered Analysis of Text Authorship</p></div>', unsafe_allow_html=True)

col1, col2 = st.columns([2, 1], gap="large")

with col1:
    st.markdown('<div class="custom-card">', unsafe_allow_html=True)
    st.subheader("Input Text for Analysis")
    input_text = st.text_area("Paste the text you want to analyze (minimum 20 words recommended):", height=250, placeholder="Example: The heart of Western culture has been fascinating for centuries...")
    
    detect_btn = st.button("DETECT AUTHORSHIP")
    st.markdown('</div>', unsafe_allow_html=True)

    if detect_btn:
        if not input_text or len(input_text.split()) < 5:
            st.warning("Please enter at least 5 words for a reliable analysis.")
        elif model is None:
            st.error("Model artifacts not found. Please ensure 'train_baseline.py' has been run successfully.")
        else:
            # Prediction
            X = vectorizer.transform([input_text])
            probs = model.predict_proba(X)[0]
            prediction = model.predict(X)[0]
            confidence = probs[prediction]
            
            # Display Result
            st.markdown('<div class="custom-card">', unsafe_allow_html=True)
            if prediction == 1:
                st.markdown('<div class="result-badge ai-badge">🤖 CLASSIFIED AS AI-GENERATED</div>', unsafe_allow_html=True)
                st.write(f"The model is **{confidence:.1%} confident** that this text was generated by an LLM.")
            else:
                st.markdown('<div class="result-badge human-badge">✍️ CLASSIFIED AS HUMAN-AUTHORED</div>', unsafe_allow_html=True)
                st.write(f"The model is **{confidence:.1%} confident** that this text was written by a human.")
            
            st.progress(confidence if prediction == 1 else 1 - confidence)
            st.markdown('</div>', unsafe_allow_html=True)

with col2:
    st.markdown('<div class="custom-card">', unsafe_allow_html=True)
    st.subheader("Linguistic Signatures")
    
    if input_text:
        analysis = analyze_signatures(input_text)
        
        st.markdown('<div class="stat-label">FORMAL TRANSITIONS (AI)</div>', unsafe_allow_html=True)
        st.markdown(f'<div class="stat-value" style="color:#a78bfa">{analysis["formal_score"]}</div>', unsafe_allow_html=True)
        
        st.markdown('<div class="stat-label">PERSONAL & INFORMAL (HUMAN)</div>', unsafe_allow_html=True)
        st.markdown(f'<div class="stat-value" style="color:#2dd4bf">{analysis["human_score"]}</div>', unsafe_allow_html=True)
        
        st.divider()
        st.info("AI models tend to use formal connectors ('however', 'overall') while humans use more personal pronouns ('I', 'we') and informal fillers.")
    else:
        st.write("Enter text to see linguistic signature breakdown.")
    st.markdown('</div>', unsafe_allow_html=True)

    st.markdown('<div class="custom-card">', unsafe_allow_html=True)
    st.subheader("Project Info")
    st.markdown("""
    - **Accuracy:** ~97% (Logistic Regression)
    - **Dataset:** HC3 (Human-ChatGPT Comparison)
    - **Architecture:** TF-IDF + Logistic Regression
    """)
    st.markdown('</div>', unsafe_allow_html=True)

# Footer
st.markdown('<div style="text-align:center; color:#94a3b8; margin-top:2rem; font-size:0.8rem">Built for AI-Generated vs Human-Authored Text Analysis Project</div>', unsafe_allow_html=True)
